# Generated by Django 2.1.15 on 2021-01-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviame', '0002_envio_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
