# Generated by Django 2.1.15 on 2021-01-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviame', '0004_auto_20210111_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='order_price',
            field=models.IntegerField(),
        ),
    ]
