# Generated by Django 2.1.15 on 2021-01-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviame', '0005_auto_20210111_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='place',
            field=models.CharField(default='Santiago', max_length=255),
            preserve_default=False,
        ),
    ]
