# Generated by Django 2.1.15 on 2021-01-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviame', '0006_envio_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='carrier_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='carrier_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
